# This is a basic workflow to help you get started with Actions

name: "Dgit Mirror Action"
description: "Pushes your github repo to Dgit"
author: "thetechtrap"
branding:
  icon: arrow-up-circle
  color: green
inputs:
  dgitWallet:
    description: 'Dgit Wallet file contents. Can be passed in using $\{{ secrets.DGIT_WALLET }}'
    required: true
  remoteUrl:
    description: "Dgit Respository remote Url, eg, dgit://wallet_address/repo_name"
    required: true
  branch:
    description: "Destination branch to push changes"
    required: false
    default: "master"
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master bran

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
runs:
  using:
    "composite"

    # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - run: npm install -g @thetechtrap/git-remote-dgit@0.1.3
      shell: bash
    - name: Add Remote
      run: |
      git remote add dgit ${{INPUT_REMOTURL}}
      shell: bash
    - name: Push to Dgit
      run: |
      git push dgit ${{INPUT_BRANCH}}
      shell: bash
      env:
        DGIT_WALLET: ${{INPUT_DGITWALLET}}
