# This is a basic workflow to help you get started with Actions

name: "Dgit Mirror Action"
description: "Pushes your github repo to Dgit"
author: "thetechtrap"
branding:
  icon: arrow-up-circle
  color: green
inputs:
  dgit_wallet:
    description: 'Dgit Wallet file contents. Can be passed in using $\{{ secrets.DGIT_WALLET }}'
    required: true
  remote_url:
    description: "Dgit Respository remote Url, eg, dgit://wallet_address/repo_name"
    required: true
  branch:
    description: "Destination branch to push changes"
    required: false
    default: "master"
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master bran


    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: npm install -g @thetechtrap/git-remote-dgit@0.1.3
    - name: Add Remote
      run: git remote add $INPUT_REMOTE_URL
    - name: Push to Dgit
      run: git push dgit $INPUT_BRANCH
      env:
        DGIT_WALLET: $DGIT_WALLET
